Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
